# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme	: "mmistakes/minimal-mistakes@4.20.2"

minimal_mistakes_skin	: "air" # "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

#Site Settings
locale            : "en-US"
title             : "Kuma Writes..."
# title_separator	: "-"
subtitle		      : "the miscellany of a simple life"
name              : &name "Kuma"
description       : &description "A collection of writings from the mind of a simple bear"
url               : https://kuma-writes.github.io
# baseurl         :
repository        : "kuma-writes/kuma-writes.github.io"
# teaser		:
logo              : "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

# search            : true
# search_full_content   : true

#email            : joonsan@mac.com
# twitter_username: jekyllrb
github_username:  kuma-writes

# Site Author
author:
  name            : *name
  #avatar         : "/assets/images/teacup_bear.png"
  bio             : "Just another nameless internet author"
  location        : "Warwick, RI"

# Build settings
# theme: minima

include:
  - _pages
exclude:
   - .sass-cache/
   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: true
      share: false


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
